### PR TITLE
added code for github workflow for auto building and deploying of the website.

### PR DESCRIPTION
**Pull request by mis-coder**
I have added the required code. Please review it and let me know if there is any problem.

closes issue #21

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Thank You so much for this PR, @mis-coder , I literally learned a lot from it , This Looks good to me 

@LordShenron , tho I have checked all these git commands , Please have an look at this

**Review by ArunTeltia — APPROVED** [review]

**Review by LordShenron — APPROVED** [review]
Looks good to me

**Comment by LordShenron** [comment]
I need a Pro flag for this one.. coz it's amazingly well written.

**Comment by ArunTeltia** [comment]
Done

**Comment by mis-coder** [comment]
I am glad I could contribute to this project.. Thank you for assigning!

**Pull request merged**
